name: Automated tests

on: [push, pull_request]

jobs:
  jest:
    name: Jest ubuntu
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "lts/iron"

      - run: npm ci

      - run: npm test
